name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: taiki-e/install-action@nextest
    - name: Test
      run: cargo nextest run
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
